import { z } from 'zod';
import {
  Gender,
  PhysicalCondition,
  MaritalStatus,
  FamilyStatus,
  Habit,
  ParentLivingStatus,
  WorkNature
} from '../../generated/prisma/client/browser';

export const personalInfoSchema = z.object({
  mobileNo: z.string().optional(),
  password: z.string().optional(),
  email: z.string().optional(),
  name: z.string().min(1, 'Name is required'),
  gender: z.nativeEnum(Gender, { message: 'Gender is required' }),
  livingCountry: z.string().min(1, 'Country is required'),
  state: z.string().min(1, 'State is required'),
  city: z.string().min(1, 'City is required'),
  houseAddress: z.string().optional(),
  religion: z.string().min(1, 'Religion is required'),
  caste: z.string().min(1, 'Caste is required'),
  subCaste: z.string().optional(),
  koottam: z.string().optional(),
  dob: z.string().refine((val) => !isNaN(Date.parse(val)), { message: "Invalid date" }),
  tob: z.string().optional(),
  lob: z.string().optional(),
  height: z.number().min(50).max(300),
  weight: z.number().min(20).max(300),
  physicalCondition: z.nativeEnum(PhysicalCondition),
  skinColour: z.string().min(1, 'Skin color is required'),
  maritalStatus: z.nativeEnum(MaritalStatus),
  familyStatus: z.nativeEnum(FamilyStatus),
  foodHabits: z.nativeEnum(Habit),
  drinkingHabits: z.nativeEnum(Habit),
  smokingHabits: z.nativeEnum(Habit),
  rasi: z.string().optional(),
  nakshatra: z.string().optional(),
  poruthaNakshatram: z.array(z.string()).default([]),
  dosham: z.string().optional(),
  
  photoUrl: z.string().optional(),
  jathakamUrl: z.string().optional(),
  casteCertificateUrl: z.string().optional(),
  rasiGrid: z.any().optional(),
  amsamGrid: z.any().optional(),
  dasaBalance: z.string().optional(),
  jathagamData: z.any().optional(),

  hideMobileNo: z.boolean().default(true),
  hideHouseAddress: z.boolean().default(true),
  hideHouseLocation: z.boolean().default(true),
  hidePhoto: z.boolean().default(false),
  educations: z.array(z.object({
    level: z.string().min(1, 'Education level is required'),
    degreeName: z.string().min(1, 'Degree is required'),
    institution: z.string().min(1, 'Institution is required'),
  })).default([]),
});

export const familyDetailsSchema = z.object({
  fatherName: z.string().optional(),
  fatherLivingStatus: z.nativeEnum(ParentLivingStatus).optional(),
  fatherStatus: z.string().optional(),
  fatherMobile: z.string().optional(),
  motherName: z.string().optional(),
  motherLivingStatus: z.nativeEnum(ParentLivingStatus).optional(),
  motherStatus: z.string().optional(),
  motherMobile: z.string().optional(),
  workNature: z.nativeEnum(WorkNature).optional(),
  salary: z.string().optional(),
  organisation: z.string().optional(),
  designation: z.string().optional(),
  workingAddress: z.string().optional(),
  googleLocation: z.string().optional(),
  rentalIncome: z.string().optional(),
  houseType: z.string().optional(),
  houseSqFt: z.string().optional(),
  siteLand: z.string().optional(),
  thottam: z.string().optional(),
  vacantLand: z.string().optional(),
  totalAssetValue: z.string().optional(),
  assetComments: z.string().optional(),
  dowryDetails: z.string().optional(),
  siblings: z.array(z.object({
    name: z.string().min(1, 'Name is required'),
    relation: z.string().min(1, 'Relation is required'),
    status: z.string().min(1, 'Status is required'),
  })).default([]),
});

export const expectationsSchema = z.object({
  expectedHeight: z.number().or(z.nan()).transform(v => isNaN(v) ? undefined : v).optional(),
  colourPreference: z.string().optional(),
  maxAgeLimit: z.number().or(z.nan()).transform(v => isNaN(v) ? undefined : v).optional(),
  dowryExpectation: z.string().optional(),
  preferredSectors: z.array(z.string()),
  preferredLocations: z.array(z.string()),
  expectedIncome: z.string().optional(),
  expectsRentalIncome: z.boolean().optional(),
  expectsThottam: z.boolean().optional(),
  expectsVacantLand: z.boolean().optional(),
  preferredDistanceRadius: z.number().or(z.nan()).transform(v => isNaN(v) ? undefined : v).optional(),
  city: z.string().optional(),
  comments: z.string().optional(),
});
